### ISSUE TITLE
Potential issue in Getting Started.ipynb > Metrics & evaluation > "format_labels"

### ISSUE THREAD

**Issue by yc443** [CAMMA-public/cholectriplet2022#1]
Hello!

I am wondering if the "format_labels" function in the Metrics & evaluation part of sample code "Getting Started.ipynb" have a slightly wrong order (and indexing) with inputs in the "res" list?

To my understanding, the "format_labels" is used to convert the raw data extracted from "sample-spatial/label.json" to a desired format. 
More specifically, to the format of input to "list2stack" function in "https://github.com/CAMMA-public/ivtmetrics > ivtmetrics/detection.py > class Detection > function list2stack", 
i.e. as stated in "list2stack" function: "#x format for a single frame: list(list): each list = [tripletID, toolID, toolProbs, x, y, w, h]".
However, I think current output of "format_labels" is giving the format of : each list = [toolID, toolProbs, toolProbs, x, y, w, h].

The screenshot below shows the original "format_labels" function and the version I modified, could you kindly have a look please?
![image](https://user-images.githubusercontent.com/92952426/175052834-c9dc0afb-87c9-47c5-af51-d0750f8a5f81.png)

Many thanks!

**Comment by nwoyecid** [comment]
The format and instruction in the https://github.com/CAMMA-public/ivtmetrics  is the correct thing. I will have a look at what is in the GettingStarted.ipynb

**Comment by yc443** [comment]
Thanks, the format and instruction is very clear! 
I think the "format_labels" function in GettingStarted.ipynb is trying to do the "dict2stack" job in "https://github.com/CAMMA-public/ivtmetrics > ivtmetrics/detection.py > class Detection", but it turns the "vid_gt" into a list(list) format, which could lead to an issue?

**Comment by nwoyecid** [comment]
You are correct. I will contact the person that wrote the GettingStarted.ipynb to cross-check with the metric library. Thank you for your input.

**Comment by yc443** [comment]
Thank you!

**Comment by nwoyecid** [comment]
For others, the correct label format should be:

![image](https://user-images.githubusercontent.com/18656978/175311325-a9d59aeb-98e4-43a9-a3c9-4d67a73e26a4.png)
